# Generated by Django 3.2.3 on 2024-11-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=7064203958, max_length=11),
            preserve_default=False,
        ),
    ]
